/*    This SQL DDL script was generated by Microsoft Visual Studio (Release Date: LOCAL BUILD). */

/*    Driver Used : Microsoft Visual Studio - Microsoft SQL Server Driver.                    */
/*    Document    : E:\Cheng\Cheng Projects\Payroll Design v1.vsd.                            */
/*    Time Created: May 08, 2013 4:02 PM.                                                     */
/*    Operation   : From Visio Generate Wizard.                                               */
/*    Connected data source : No connection.                                                  */
/*    Connected server      : No connection.                                                  */
/*    Connected database    : Not applicable.                                                 */



SET QUOTED_IDENTIFIER ON

go


/* Create PayrollDB database.                                                                 */
use master  

go

create database "PayrollDB"  

go

use "PayrollDB"  

go

/* Create new table "Position".                                                               */
/* "Position" : Table of Position                                                             */
/* 	"PositionID" : PositionID identifies Position                                             */
/* 	"PositionName" : PositionName is of Position                                              */
/* 	"Rate" : Rate is of Position                                                              */  
create table "Position" ( 
	"PositionID" smallint identity not null,
	"PositionName" varchar(50) not null,
	"Rate" float not null)  

go

alter table "Position"
	add constraint "Position_PK" primary key ("PositionID")   


go

/* Create new table "User".                                                                   */
/* "User" : Table of User                                                                     */
/* 	"UserID" : UserID identifies User                                                         */
/* 	"PositionID" : PositionID partly identifies User                                          */
/* 	"FirstName" : FirstName is of User                                                        */
/* 	"MiddleName" : MiddleName is of User                                                      */
/* 	"LastName" : LastName is of User                                                          */  
create table "User" ( 
	"UserID" uniqueidentifier not null,
	"PositionID" smallint not null,
	"FirstName" varchar(50) not null,
	"MiddleName" varchar(50) not null,
	"LastName" varchar(50) not null)  

go

alter table "User"
	add constraint "User_PK" primary key ("UserID")   


go

/* Add foreign key constraints to table "User".                                               */
alter table "User"
	add constraint "Position_User_FK1" foreign key (
		"PositionID")
	 references "Position" (
		"PositionID") on update no action on delete no action  

go


/* This is the end of the Microsoft Visual Studio generated SQL DDL script.                   */
